{
 "title": "PurpleAir Station RP@70m",
 "description": "Py's PurpleAir Weather Rocky Point Station 70m",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "15m",
 "templating": {
  "list": [
   { "name": "cost_per_kWh", "query": "0.12" }
  ]
 },
 "panels": [
  {
   "title": "PurpleAIr AQI",
   "type": "stat",
   "description": "This panel shows the current power being used at home. ",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "AQI",
     "groupBy": [
      { "params": [ "10m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "PurpleAirQuality",
     "select": [
      [
       { "params": [ "pm2.5_aqi_b" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Py's PurpleAIr Station Rocky Point @70m",
   "type": "stat",
   "description": "This panel shows the current power being used at home. ",
   "gridPos": { "h": 4, "w": 9, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "conμgm3" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "PM 10",
     "groupBy": [
      { "params": [ "10m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "PurpleAirQuality",
     "select": [
      [
       { "params": [ "pm10_0_atm" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "PM 2.5",
     "groupBy": [
      { "params": [ "10m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "PurpleAirQuality",
     "select": [
      [
       { "params": [ "pm2_5_atm" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "PM 1.0",
     "groupBy": [
      { "params": [ "10m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "PurpleAirQuality",
     "select": [
      [
       { "params": [ "pm1_0_atm" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "PurpleAIr Station Index for Air Quality ",
   "type": "stat",
   "description": "Experimental VOC (Bosch Static IAQ) BME680\n\n0-50 Excellent\n51-100 Good\n101-150 Lightly Polluted -- ventilation suggested\n151-200 Moderately Polluted\n201-250 Heavy Polluted, Exposure may have health effects depending on type of VOC\n251... Very bad, run....\n351... Dangerously polluted, neurotoxic effects possible\n\nhttps://www.bosch-sensortec.com/media/boschsensortec/downloads/datasheets/bst-bme680-ds001.pdf",
   "gridPos": { "h": 4, "w": 3, "x": 13, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "VOC",
     "groupBy": [
      { "params": [ "10m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "PurpleAirQuality",
     "select": [
      [
       { "params": [ "gas_680" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "PurpleAIr Station",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Temp in C",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "PurpleAirQuality",
     "query": "SELECT (mean(\"current_temp_f\")-32)*5/9-5 FROM \"PurpleAirQuality\" WHERE $timeFilter GROUP BY time(20m) fill(null)",
     "select": [
      [
       { "params": [ "current_temp_f" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "PurpleAIr Station",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "humidity" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "RH %",
     "groupBy": [
      { "params": [ "10m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "PurpleAirQuality",
     "query": "SELECT mean(\"current_humidity\") FROM \"PurpleAirQuality\" WHERE $timeFilter GROUP BY time(10m) fill(null)",
     "select": [
      [
       { "params": [ "current_humidity" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "PurpleAIr Station",
   "type": "stat",
   "description": "This panel shows the current power being used at home. ",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "pressurehpa" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "P in mbar",
     "groupBy": [
      { "params": [ "10m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "PurpleAirQuality",
     "select": [
      [
       { "params": [ "pressure" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Solar Production Now",
   "type": "stat",
   "description": "PV production",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "solar",
     "select": [
      [
       { "params": [ "power" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "PurpleAIr Particular Matter",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "conμgm3", "label": "PM" }
   ],
   "targets": [
    {
     "alias": "PM 2.5",
     "groupBy": [
      { "params": [ "10m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "PurpleAirQuality",
     "select": [
      [
       { "params": [ "pm2_5_atm" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "PM 1.0",
     "groupBy": [
      { "params": [ "10m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "PurpleAirQuality",
     "select": [
      [
       { "params": [ "pm1_0_atm" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "PM 10",
     "groupBy": [
      { "params": [ "10m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "PurpleAirQuality",
     "select": [
      [
       { "params": [ "pm10_0_atm" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "PurpleAir:Temperature",
   "type": "graph",
   "description": "This panel shows the current power being used at home. ",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "celsius", "label": "Temp in C" }
   ],
   "targets": [
    {
     "alias": "Temp in C",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "PurpleAirQuality",
     "query": "SELECT (mean(\"current_temp_f\")-32)*5/9-5 FROM \"PurpleAirQuality\" WHERE $timeFilter GROUP BY time(20m) fill(null)",
     "select": [
      [
       { "params": [ "current_temp_f" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "PurpleAir: Pressure",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "pressurehpa" } },
   "yaxes": [
    { "format": "pressurehpa", "label": "Pressure" }
   ],
   "targets": [
    {
     "alias": "Pressure",
     "groupBy": [
      { "params": [ "10m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "PurpleAirQuality",
     "query": "SELECT (mean(\"current_temp_f\")-32)*5/9-5 FROM \"PurpleAirQuality\" WHERE $timeFilter GROUP BY time(20m) fill(null)",
     "select": [
      [
       { "params": [ "pressure" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "PurpleAir: RH",
   "type": "graph",
   "description": "Purple Air RH data",
   "gridPos": { "h": 9, "w": 12, "x": 1, "y": 35 },
   "yaxes": [
    { "format": "humidity" }
   ],
   "targets": [
    {
     "alias": "RH%",
     "groupBy": [
      { "params": [ "10m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "PurpleAirQuality",
     "query": "SELECT (mean(\"current_temp_f\")-32)*5/9-5 FROM \"PurpleAirQuality\" WHERE $timeFilter GROUP BY time(20m) fill(null)",
     "select": [
      [
       { "params": [ "current_humidity" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Solar Power Generation",
   "type": "graph",
   "description": "By default, this chart will show zero, because you have to set up solar integration in the code manually. See the Wiki section titled \"Solar PV Integration\"",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 44 },
   "yaxes": [
    { "format": "watt", "label": "Watts" }
   ],
   "targets": [
    {
     "alias": "PV Production",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "solar",
     "query": "SELECT mean(\"power\") FROM \"solar\" WHERE $timeFilter GROUP BY time($__interval) fill(none)",
     "select": [
      [
       { "params": [ "power" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "PurpleAir: RH",
   "type": "graph",
   "description": "Purple Air RH data",
   "gridPos": { "h": 9, "w": 12, "x": 1, "y": 53 },
   "yaxes": [
    { "format": "humidity" }
   ],
   "targets": [
    {
     "alias": "RH%",
     "groupBy": [
      { "params": [ "10m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "PurpleAirQuality",
     "query": "SELECT (mean(\"current_temp_f\")-32)*5/9-5 FROM \"PurpleAirQuality\" WHERE $timeFilter GROUP BY time(20m) fill(null)",
     "select": [
      [
       { "params": [ "current_humidity" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "PurpleAir: Bosch AQI Gas",
   "type": "graph",
   "description": "PurpleAir: Bosch Static AQI Gas680",
   "gridPos": { "h": 9, "w": 12, "x": 1, "y": 62 },
   "yaxes": [
    { "format": "string", "label": "Bosch AQI Gas" }
   ],
   "targets": [
    {
     "alias": "Bosch AQI Gas",
     "groupBy": [
      { "params": [ "10m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "PurpleAirQuality",
     "query": "SELECT (mean(\"current_temp_f\")-32)*5/9-5 FROM \"PurpleAirQuality\" WHERE $timeFilter GROUP BY time(20m) fill(null)",
     "select": [
      [
       { "params": [ "gas_680" ], "type": "field" },
       {
        "params": [],
        "type": "median"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "SSSM",
   "type": "graph",
   "description": "This panel shows the current power being used at home. ",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 71 },
   "yaxes": [
    { "format": "arcsec", "label": "SSSM Arcs" }
   ],
   "targets": [
    {
     "alias": "SSSM Arcs MIN",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "arcs",
     "query": "SELECT min(\"value\") FROM \"arcs\" WHERE $timeFilter GROUP BY time($__interval) fill(0)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "min"
       }
      ]
     ]
    },
    {
     "alias": "SSSM Arcs MAX",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "arcs",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ]
    },
    {
     "alias": "Intensity",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "refint",
     "query": "SELECT mean(\"value\") FROM \"refint\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Battery Value",
     "groupBy": [
      { "params": [ "5m" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "battery",
     "query": "SELECT mean(\"value\") FROM \"refint\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ " / 100" ], "type": "math" }
      ]
     ]
    },
    {
     "alias": "SSSM Arcs 1 Minute Median",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "arcs",
     "query": "SELECT min(\"value\") FROM \"arcs\" WHERE $timeFilter GROUP BY time($__interval) fill(0)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "median"
       }
      ]
     ]
    },
    {
     "alias": "SSSM Arcs Now",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "arcs",
     "query": "SELECT min(\"value\") FROM \"arcs\" WHERE $timeFilter GROUP BY time($__interval) fill(0)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  }
 ]
}